### PR TITLE
Editing-Form-Code

### PR DESCRIPTION
**Pull request by ITsunilthapa**
All changes into one form

### CODE REVIEW

**Comment by ITsunilthapa** [comment]
I got an error while submitting the form:
Form is not valid
[
{
"code": "OBJECT_ADDITIONAL_PROPERTIES",
"params": [
[
"meta"
]
],
"message": "Additional properties not allowed: meta",
"path": "#/"
}
]

**Comment by randyhoulahan** [comment]
> I got an error while submitting the form:
> Form is not valid
> [
> {
> "code": "OBJECT_ADDITIONAL_PROPERTIES",
> "params": [
> [
> "meta"
> ]
> ],
> "message": "Additional properties not allowed: meta",
> "path": "#/"
> }
> ]

Basically, "Additional properties not allowed: meta".  You are sending a property on the object that is not permitted.  The meta property is only created and edited by the server.  When you get the action object from server it has meta.  When sending for update it must be removed.  delete actionObject.meta; ----- prior to sending

**Comment by randyhoulahan** [comment]
Screen Shot 2021-09-15 at 8 49 04 AM

Comment out or add v-if="false" to half of the form.  Then run and if you still see the error,  the error is in the  code not removed.  Repeat this until you find the field vee-validate cannot find.  Try to find why its not found, once identified, an if statement renders the section only after a prop is true?

**Comment by randyhoulahan** [comment]
There is a strange bug, look into it but do not spend more than one hour.  Some form fields are not populating.  It appears to happen when there is too much strain on the gpu.  How can we protect this from happening?

https://user-images.githubusercontent.com/13351610/133437025-54e854cc-2dbd-4356-a540-a61ed5e729cf.mov

**Comment by randyhoulahan** [comment]
I have cleaned your branch as there are commits from me in the draft as well.  Your work should be rebased onto branch [v.1](https://github.com/scbd/action-agenda-components/tree/v.1.)  I did this and named the branch [v.1.form.edit.](https://github.com/scbd/action-agenda-components/tree/v.1.form.edit)  Please work from this branch to continue.

Please reset the last commit on that branch and recommit so it shows you doing the work not me.  Then force push.  Before force pushing please branch a backup of v1 just to be on the safe side.

**Pull request closed without merging**
