### PR TITLE
form-edits-latest

### PR DESCRIPTION
**Pull request by ITsunilthapa**
Added actor block

### CODE REVIEW

**Comment by randyhoulahan** [comment]
Looking good so far, we will continue on and clean up the code.  First proceed with resolving issue when an existing action has type "identifier": "ORG-TYPE-OTHER" and not corresponding property LString typeOther to initialize it.  Ensuring if ORG-TYPE-OTHER is select LString typeOther is required.

Proceed on to testing the editability on this actor section.

**Review by randyhoulahan — APPROVED** [review]

**Comment by hmalik129** [comment]
Great work Sunil. It looks good!

**Comment by PhantomGhost0308** [comment]
Well done Sunil, I think it's great! (Sorry for my belated message)

**Comment by ITsunilthapa** [comment]
Thank you everyone for your comments.

**Pull request closed without merging**
